# This is a hands-on task to create the cloudformation stack with
# 2 EC2 instances in total & one s3 bucket
# Webserver with 8gb EBS
# Appserver with 10gb EBS
# One S3 bucket to store invoice pds files

Parameters:
  InstanceTypeParam:
    Type: String
    Default: "t2.micro" 
    Description: "EC2 Type for creation"

Resources: 
  KamsiWebserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0022f774911c1d690"
      InstanceType: !Ref InstanceTypeParam
      KeyName: "Kamsi-Bastion-KP"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: "100"
          DeleteOnTermination: "true"
          VolumeSize: "8"
  KamsiAppserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0193dcf9aa4f5654e"
      InstanceType: "t2.micro"
      KeyName: "Kamsi-Bastion-KP"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: "100"
          DeleteOnTermination: "true"
          VolumeSize: "10"
  KamsiS3InvoiceBucket:
    Type: "AWS::S3::Bucket"
      
